import bcrypt from 'bcryptjs';

export const encryptPassword = async (password) => {

    const salt = await bcrypt.genSalt(10);
    return await bcrypt.hash(password, salt);
}

export const validatePassword = async (password, receivedPassword) => {
    return await bcrypt.compare(password, receivedPassword);
}

export const generatePassword = () => {
    const alphanumeric = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    let autoGeneratedPassword = '';
    for (let i = 0; i < 8; i++)
        autoGeneratedPassword += alphanumeric[Math.floor(Math.random() * alphanumeric.length)];
    return autoGeneratedPassword;
}

export const methods = {
    encryptPassword,
    validatePassword,
    generatePassword
}